name: Publish papermc-bibliothek to test pypi

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Setup ğŸ’¾"
        run: rm -r ./build ./dist
      - name: "Build package ğŸ—"
        run: python setup.py sdist bdist_wheel
      - name: "Publish package ğŸ›«"
        run: python -m twine upload --repository testpypi dist/* --username __token__ --password ${{ PYPI_TEST_TOKEN }}